// frontend/src/views/Chat.vue
<template>
  <div class="chat-page">
    <el-row :gutter="16" class="full-height">
      <el-col :span="6" class="full-height">
        <el-card class="panel full-height">
          <template #header>
            <div class="header-row">
              <span>Chat Sessions</span>
              <el-button type="primary" size="small" @click="createSession">新建</el-button>
            </div>
          </template>
          <div class="session-list">
            <div
              v-for="session in sessions"
              :key="session.id"
              class="session-item"
              :class="{ active: session.id === currentSessionId }"
              @click="switchSession(session.id)"
            >
              <div class="title">{{ session.title || `Session #${session.id}` }}</div>
              <div class="time">{{ formatDate(session.updatedAt || session.createdAt) }}</div>
            </div>
          </div>
        </el-card>
      </el-col>

      <el-col :span="18" class="full-height">
        <el-card class="panel full-height">
          <template #header>
            <div class="header-row">
              <span>Chat</span>
              <div class="actions">
                <el-select
                  v-model="selectedDatasetId"
                  clearable
                  placeholder="可选：指定分析数据表"
                  style="width: 260px"
                >
                  <el-option
                    v-for="ds in sessionDatasets"
                    :key="ds.id"
                    :label="`${ds.name} (${ds.tableName})`"
                    :value="ds.id"
                  />
                </el-select>

                <el-upload
                  :show-file-list="false"
                  :http-request="handleUpload"
                  :before-upload="beforeUpload"
                  accept=".csv,.xlsx,.xls"
                >
                  <el-button :loading="uploading">上传数据</el-button>
                </el-upload>

                <el-button type="primary" @click="openPromoteDialog">升级为 Workplace</el-button>
              </div>
            </div>
          </template>

          <div class="chat-body">
            <div ref="messageContainerRef" class="messages">
              <div
                v-for="msg in messages"
                :key="msg.id"
                class="message"
                :class="(msg.role || '').toLowerCase()"
              >
                <div class="bubble">
                  <div class="meta">{{ msg.role }}</div>
                  <div class="content">{{ msg.content }}</div>
                </div>
              </div>
            </div>

            <div v-if="lastResult && lastResult.success" class="result-box">
              <div class="result-title">最近一次分析结果</div>
              <div class="result-summary">{{ lastResult.summary || '分析已完成' }}</div>

              <el-table
                v-if="lastResult.data && lastResult.data.length > 0"
                :data="lastResult.data.slice(0, 20)"
                border
                size="small"
                max-height="220"
              >
                <el-table-column
                  v-for="col in resultColumns"
                  :key="col"
                  :prop="col"
                  :label="col"
                  min-width="120"
                  show-overflow-tooltip
                />
              </el-table>

              <pre v-if="lastResult.generatedCodeOrSql" class="code"><code>{{ lastResult.generatedCodeOrSql }}</code></pre>
            </div>
          </div>

          <div class="composer">
            <el-input
              v-model="inputText"
              type="textarea"
              :rows="3"
              resize="none"
              placeholder="输入问题：可直接聊天，也可以结合已上传数据分析。"
              @keydown.ctrl.enter.prevent="sendMessage"
            />
            <div class="composer-actions">
              <span class="hint">Ctrl + Enter 发送</span>
              <el-button type="primary" :loading="analyzing" @click="sendMessage">发送</el-button>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <el-dialog v-model="promoteVisible" title="升级为 Workplace" width="520px">
      <el-form label-position="top">
        <el-form-item label="Workplace 名称">
          <el-input v-model="workspaceName" />
        </el-form-item>
        <el-form-item label="描述（可选）">
          <el-input v-model="workspaceDescription" type="textarea" :rows="5" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="promoteVisible = false">取消</el-button>
        <el-button type="primary" :loading="promoting" @click="promoteToWorkspace">确认升级</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, nextTick, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { chatApi } from '@/api'

const router = useRouter()

const sessions = ref([])
const currentSessionId = ref(null)
const messages = ref([])
const sessionDatasets = ref([])
const selectedDatasetId = ref(null)
const inputText = ref('')
const analyzing = ref(false)
const uploading = ref(false)
const lastResult = ref(null)
const messageContainerRef = ref(null)

const promoteVisible = ref(false)
const promoting = ref(false)
const workspaceName = ref('')
const workspaceDescription = ref('')

const resultColumns = computed(() => {
  if (!lastResult.value?.data?.length) return []
  return Object.keys(lastResult.value.data[0])
})

const loadSessions = async () => {
  try {
    const res = await chatApi.getSessions()
    if (res.success) {
      sessions.value = res.data || []
      if (!sessions.value.length) {
        await createSession()
        return
      }
      if (!currentSessionId.value || !sessions.value.find(s => s.id === currentSessionId.value)) {
        currentSessionId.value = sessions.value[0].id
      }
      await loadSessionData()
    }
  } catch (error) {
    ElMessage.error('加载聊天会话失败')
    console.error(error)
  }
}

const createSession = async () => {
  try {
    const res = await chatApi.createSession()
    if (res.success) {
      currentSessionId.value = res.data.id
      await loadSessions()
    } else {
      ElMessage.error(res.message || '创建会话失败')
    }
  } catch (error) {
    ElMessage.error('创建会话失败')
  }
}

const switchSession = async (sessionId) => {
  if (!sessionId) return
  currentSessionId.value = sessionId
  lastResult.value = null
  selectedDatasetId.value = null
  await loadSessionData()
}

const loadSessionData = async () => {
  if (!currentSessionId.value) return
  await Promise.all([loadMessages(), loadSessionDatasets()])
  await scrollToBottom()
}

const loadMessages = async () => {
  if (!currentSessionId.value) return
  const res = await chatApi.getMessages(currentSessionId.value)
  if (res.success) {
    messages.value = res.data || []
  }
}

const loadSessionDatasets = async () => {
  if (!currentSessionId.value) return
  const res = await chatApi.getDatasets(currentSessionId.value)
  if (res.success) {
    sessionDatasets.value = res.data || []
    if (selectedDatasetId.value && !sessionDatasets.value.find(d => d.id === selectedDatasetId.value)) {
      selectedDatasetId.value = null
    }
  }
}

const beforeUpload = (file) => {
  const okType = ['.csv', '.xlsx', '.xls'].some(ext => file.name.toLowerCase().endsWith(ext))
  if (!okType) {
    ElMessage.error('只支持 CSV/Excel 文件')
    return false
  }
  const isLt100M = file.size / 1024 / 1024 < 100
  if (!isLt100M) {
    ElMessage.error('文件大小不能超过100MB')
    return false
  }
  return true
}

const handleUpload = async ({ file }) => {
  if (!currentSessionId.value) return
  uploading.value = true
  try {
    const res = await chatApi.upload(currentSessionId.value, file, file.name)
    if (res.success) {
      ElMessage.success('上传成功')
      await loadSessionData()
    } else {
      ElMessage.error(res.message || '上传失败')
    }
  } catch (error) {
    ElMessage.error(error?.response?.data?.message || '上传失败')
  } finally {
    uploading.value = false
  }
}

const sendMessage = async () => {
  const query = inputText.value.trim()
  if (!query) return
  if (!currentSessionId.value) {
    ElMessage.warning('请先创建会话')
    return
  }
  analyzing.value = true
  try {
    const res = await chatApi.analyze(currentSessionId.value, query, selectedDatasetId.value)
    if (res.success) {
      inputText.value = ''
      lastResult.value = res
      await loadMessages()
      await loadSessions()
      await scrollToBottom()
    } else {
      ElMessage.error(res.message || '分析失败')
    }
  } catch (error) {
    ElMessage.error(error?.response?.data?.message || '分析失败')
  } finally {
    analyzing.value = false
  }
}

const openPromoteDialog = () => {
  if (!currentSessionId.value) return
  if (!sessionDatasets.value.length) {
    ElMessage.warning('当前会话没有可升级的数据集，请先上传数据')
    return
  }
  const active = sessions.value.find(s => s.id === currentSessionId.value)
  workspaceName.value = active?.title ? `${active.title}-Workplace` : `Workplace-${Date.now()}`
  workspaceDescription.value = ''
  promoteVisible.value = true
}

const promoteToWorkspace = async () => {
  if (!workspaceName.value.trim()) {
    ElMessage.warning('请输入 Workplace 名称')
    return
  }
  promoting.value = true
  try {
    const res = await chatApi.promote(currentSessionId.value, {
      workspaceName: workspaceName.value.trim(),
      description: workspaceDescription.value
    })
    if (res.success) {
      ElMessage.success('升级成功，正在跳转到 Workplace 分析页')
      promoteVisible.value = false
      router.push({
        path: '/analysis',
        query: { groupId: res.data.id }
      })
    } else {
      ElMessage.error(res.message || '升级失败')
    }
  } catch (error) {
    ElMessage.error(error?.response?.data?.message || '升级失败')
  } finally {
    promoting.value = false
  }
}

const scrollToBottom = async () => {
  await nextTick()
  if (messageContainerRef.value) {
    messageContainerRef.value.scrollTop = messageContainerRef.value.scrollHeight
  }
}

const formatDate = (dateStr) => {
  if (!dateStr) return ''
  return new Date(dateStr).toLocaleString('zh-CN')
}

onMounted(async () => {
  await loadSessions()
})
</script>

<style scoped>
.chat-page {
  height: calc(100vh - 120px);
}

.full-height {
  height: 100%;
}

.panel {
  height: 100%;
  display: flex;
  flex-direction: column;
}

:deep(.panel .el-card__body) {
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
}

.header-row {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.session-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
  overflow-y: auto;
}

.session-item {
  border: 1px solid #eceef2;
  border-radius: 10px;
  padding: 10px;
  cursor: pointer;
  background: #fff;
}

.session-item:hover {
  border-color: #a9c6ff;
}

.session-item.active {
  border-color: #409eff;
  background: #f0f7ff;
}

.session-item .title {
  font-size: 14px;
  font-weight: 600;
}

.session-item .time {
  color: #909399;
  margin-top: 4px;
  font-size: 12px;
}

.chat-body {
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.messages {
  flex: 1;
  min-height: 0;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding-right: 4px;
}

.message {
  display: flex;
}

.message.user {
  justify-content: flex-end;
}

.message.assistant,
.message.system {
  justify-content: flex-start;
}

.bubble {
  max-width: 80%;
  border-radius: 12px;
  padding: 10px 12px;
  border: 1px solid #ebeef5;
  background: #fff;
}

.message.user .bubble {
  background: #409eff;
  color: #fff;
  border-color: #409eff;
}

.meta {
  font-size: 12px;
  opacity: 0.75;
}

.content {
  white-space: pre-wrap;
  line-height: 1.5;
  margin-top: 4px;
}

.result-box {
  border-top: 1px dashed #dcdfe6;
  padding-top: 10px;
}

.result-title {
  font-weight: 600;
  margin-bottom: 8px;
}

.result-summary {
  margin-bottom: 8px;
  color: #606266;
  line-height: 1.6;
}

.code {
  margin-top: 8px;
  background: #1f2430;
  color: #dfe6f3;
  border-radius: 8px;
  padding: 10px;
  overflow-x: auto;
  font-size: 12px;
}

.composer {
  border-top: 1px solid #ebeef5;
  padding-top: 10px;
}

.composer-actions {
  margin-top: 8px;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.hint {
  color: #909399;
  font-size: 12px;
}
</style>

// frontend-next/src/app/(dashboard)/chat/page.tsx
"use client";

import { Suspense, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { toast } from "sonner";
import { ArrowUp, FolderUp, Loader2, Upload } from "lucide-react";
import { artifactApi, chatApi } from "@/lib/api/client";
import type { AnalysisResult, Artifact, ChatMessage, ChatSession, Dataset } from "@/lib/types";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { useLanguage } from "@/components/providers/language-provider";

function formatTime(raw: string | undefined, localeTag: string) {
  if (!raw) return "";
  const date = new Date(raw);
  if (Number.isNaN(date.valueOf())) return "";
  return date.toLocaleString(localeTag, {
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function parsePreview(value?: string | null) {
  if (!value) return [];
  try {
    const parsed = JSON.parse(value) as Record<string, unknown>[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function ResultTable({ rows }: { rows: Record<string, unknown>[] }) {
  const columns = rows.length ? Object.keys(rows[0]) : [];
  if (!rows.length) return null;

  return (
    <div className="mt-5 overflow-hidden border border-[color:var(--color-border-primary)] bg-[color:var(--color-background-primary)]">
      <div className="max-h-[280px] overflow-auto">
        <table className="min-w-full border-collapse text-left text-sm">
          <thead className="sticky top-0 bg-[color:var(--color-background-secondary)]">
            <tr>
              {columns.map((column) => (
                <th
                  key={column}
                  className="border-b border-[color:var(--color-border-primary)] px-4 py-3 font-mono text-[11px] font-black uppercase text-[color:var(--color-text-primary)]"
                >
                  {column}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.slice(0, 10).map((row, rowIndex) => (
              <tr key={rowIndex} className="border-t border-[color:var(--color-border-tertiary)]">
                {columns.map((column) => (
                  <td key={column} className="px-4 py-3 text-[color:var(--color-text-secondary)]">
                    {String(row[column] ?? "")}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function ChatPageContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { t, localeTag } = useLanguage();

  const sessionParam = useMemo(() => {
    const raw = Number(searchParams.get("session"));
    return Number.isFinite(raw) && raw > 0 ? raw : null;
  }, [searchParams]);

  const [sessions, setSessions] = useState<ChatSession[]>([]);
  const [activeSessionId, setActiveSessionId] = useState<number | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [datasets, setDatasets] = useState<Dataset[]>([]);
  const [selectedDatasetId, setSelectedDatasetId] = useState<number | undefined>(undefined);
  const [input, setInput] = useState("");
  const [lastResult, setLastResult] = useState<AnalysisResult | null>(null);
  const [recentArtifacts, setRecentArtifacts] = useState<Artifact[]>([]);
  const [loadingSessions, setLoadingSessions] = useState(true);
  const [loadingMessages, setLoadingMessages] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [promoteOpen, setPromoteOpen] = useState(false);
  const [workspaceName, setWorkspaceName] = useState("");
  const [workspaceDesc, setWorkspaceDesc] = useState("");
  const [promoting, setPromoting] = useState(false);
  const [showCode, setShowCode] = useState(false);

  const fileInputRef = useRef<HTMLInputElement | null>(null);
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const missingSessionRef = useRef<number | null>(null);

  const resetConversationView = useCallback(() => {
    setMessages([]);
    setDatasets([]);
    setSelectedDatasetId(undefined);
    setInput("");
    setLastResult(null);
    setRecentArtifacts([]);
    setShowCode(false);
  }, []);

  const initialize = useCallback(async () => {
    setLoadingSessions(true);
    try {
      const res = await chatApi.getSessions();
      setSessions(res.data ?? []);
    } catch (error) {
      toast.error((error as Error).message || t("failed_load_sessions"));
    } finally {
      setLoadingSessions(false);
    }
  }, [t]);

  const loadSessionPayload = useCallback(
    async (sessionId: number) => {
      setLoadingMessages(true);
      try {
        const [messageRes, datasetRes, artifactRes] = await Promise.all([
          chatApi.getMessages(sessionId),
          chatApi.getDatasets(sessionId),
          artifactApi.recent({ sessionId, limit: 8 }),
        ]);
        const nextDatasets = datasetRes.data ?? [];
        setMessages(messageRes.data ?? []);
        setDatasets(nextDatasets);
        setRecentArtifacts(artifactRes.data ?? []);
        setSelectedDatasetId((currentDatasetId) =>
          currentDatasetId && !nextDatasets.some((dataset) => dataset.id === currentDatasetId)
            ? undefined
            : currentDatasetId
        );
      } catch (error) {
        toast.error((error as Error).message || t("failed_load_session_details"));
      } finally {
        setLoadingMessages(false);
      }
    },
    [t]
  );

  useEffect(() => {
    void initialize();
  }, [initialize]);

  useEffect(() => {
    const reloadSessions = () => {
      void initialize();
    };
    window.addEventListener("chat-sessions-changed", reloadSessions);
    return () => window.removeEventListener("chat-sessions-changed", reloadSessions);
  }, [initialize]);

  useEffect(() => {
    if (!scrollRef.current) return;
    scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [messages, lastResult, recentArtifacts]);

  useEffect(() => {
    if (loadingSessions) return;

    if (!sessions.length) {
      missingSessionRef.current = null;
      setActiveSessionId(null);
      resetConversationView();
      return;
    }

    if (sessionParam && sessions.some((session) => session.id === sessionParam)) {
      missingSessionRef.current = null;
      setActiveSessionId(sessionParam);
      return;
    }

    if (sessionParam && !sessions.some((session) => session.id === sessionParam)) {
      resetConversationView();
      setActiveSessionId(null);

      if (missingSessionRef.current !== sessionParam) {
        missingSessionRef.current = sessionParam;
        void initialize();
        return;
      }

      missingSessionRef.current = null;
      const fallback = sessions[0]?.id;
      if (fallback) {
        setActiveSessionId(fallback);
        router.replace(`/chat?session=${fallback}`);
      } else {
        router.replace("/chat");
      }
      return;
    }

    const fallback = sessions[0].id;
    missingSessionRef.current = null;
    setActiveSessionId(fallback);
    router.replace(`/chat?session=${fallback}`);
  }, [initialize, loadingSessions, resetConversationView, router, sessionParam, sessions]);

  useEffect(() => {
    resetConversationView();
    if (!activeSessionId) {
      setLoadingMessages(false);
      return;
    }
    void loadSessionPayload(activeSessionId);
  }, [activeSessionId, loadSessionPayload, resetConversationView]);

  const ensureSession = useCallback(async (titleHint?: string) => {
    if (activeSessionId) return activeSessionId;

    try {
      const normalizedTitle = titleHint?.trim().replace(/\s+/g, " ");
      const sessionTitle = normalizedTitle
        ? normalizedTitle.slice(0, 28)
        : t("new_chat_session");
      const created = await chatApi.createSession(sessionTitle);
      const next = created.data;
      if (!next) return null;
      setSessions((prev) => [next, ...prev]);
      setActiveSessionId(next.id);
      router.replace(`/chat?session=${next.id}`);
      window.dispatchEvent(new Event("chat-sessions-changed"));
      return next.id;
    } catch (error) {
      toast.error((error as Error).message || t("failed_create_session"));
      return null;
    }
  }, [activeSessionId, router, t]);

  async function sendMessage() {
    if (analyzing) return;

    const query = input.trim();
    if (!query) return;

    const sessionBeforeSend = activeSessionId ? sessions.find((session) => session.id === activeSessionId) : null;
    const shouldRenameActiveSession =
      !!activeSessionId &&
      messages.length === 0 &&
      (!sessionBeforeSend?.title ||
        sessionBeforeSend.title === t("new_chat_session") ||
        sessionBeforeSend.title.includes("新建") ||
        sessionBeforeSend.title.toLowerCase().includes("new"));

    const sessionId = await ensureSession(query);
    if (!sessionId) {
      toast.error(t("no_active_session"));
      return;
    }

    setAnalyzing(true);
    setMessages((prev) => [...prev, { id: Date.now(), role: "USER", content: query, sessionId }]);
    setInput("");
    setShowCode(false);

    try {
      if (shouldRenameActiveSession) {
        const normalizedTitle = query.replace(/\s+/g, " ").slice(0, 28);
        const updated = await chatApi.updateSession(sessionId, normalizedTitle);
        if (updated.data) {
          setSessions((prev) => prev.map((session) => (session.id === sessionId ? updated.data! : session)));
          window.dispatchEvent(new Event("chat-sessions-changed"));
        }
      }
      const result = await chatApi.analyze(sessionId, query, selectedDatasetId);
      setLastResult(result);
      if (!result.success) {
        toast.error(result.message || t("analysis_failed"));
      }
      await initialize();
      await loadSessionPayload(sessionId);
    } catch (error) {
      toast.error((error as Error).message || t("analysis_request_failed"));
    } finally {
      setAnalyzing(false);
    }
  }

  async function triggerUpload(file?: File) {
    const sessionId = await ensureSession(file?.name);
    if (!sessionId || !file) return;

    setUploading(true);
    try {
      const res = await chatApi.uploadDataset(sessionId, file, file.name);
      if (!res.success) {
        toast.error(res.message || t("upload_failed"));
        return;
      }
      toast.success(t("dataset_uploaded_chat"));
      await initialize();
      await loadSessionPayload(sessionId);
    } catch (error) {
      toast.error((error as Error).message || t("upload_failed"));
    } finally {
      setUploading(false);
    }
  }

  async function promoteToWorkspace() {
    if (!activeSessionId) return;
    if (!workspaceName.trim()) {
      toast.error(t("workspace_name_required"));
      return;
    }

    setPromoting(true);
    try {
      const res = await chatApi.promote(activeSessionId, workspaceName.trim(), workspaceDesc.trim());
      if (!res.success || !res.data?.id) {
        toast.error(res.message || t("promotion_failed"));
        return;
      }
      toast.success(t("promoted_to_workplace", { name: res.data.name }));
      window.location.href = `/workspace?groupId=${res.data.id}`;
    } catch (error) {
      toast.error((error as Error).message || t("promotion_failed"));
    } finally {
      setPromoting(false);
    }
  }

  const previewArtifacts = recentArtifacts.slice(0, 4);
  const isEmptyState = !loadingMessages && !messages.length && !lastResult;
  const hasConversation = messages.length > 0 || !!lastResult;

  const composer = (
    <div className="mx-auto w-full max-w-[860px]">
      <div className="relay-panel">
        <div className="flex items-center justify-between border-b border-[color:var(--color-border-tertiary)] px-4 py-3">
          <span className="font-mono text-[11px] font-black uppercase tracking-[0.08em] text-[color:var(--color-text-tertiary)]">
            analysis prompt
          </span>
          <span className="flex items-center gap-2 font-mono text-[11px] uppercase text-[color:var(--color-text-tertiary)]">
            <span className="relay-status-dot" />
            context ready
          </span>
        </div>
        <div className="px-4 pb-4 pt-4">
        <Textarea
          value={input}
          onChange={(event) => setInput(event.target.value)}
          placeholder="输入分析问题..."
          className="min-h-[104px] resize-none rounded-[10px] border-none !bg-[color:var(--color-background-secondary)] px-4 py-3 text-[17px] leading-8 shadow-none outline-none hover:!bg-[color:var(--color-background-secondary)] focus:!bg-[color:var(--color-background-secondary)] focus:border-none focus:outline-none focus-visible:!bg-[color:var(--color-background-secondary)] focus-visible:border-transparent focus-visible:shadow-none focus-visible:ring-0 focus-visible:ring-offset-0"
          onKeyDown={(event) => {
            if (event.key === "Enter" && !event.shiftKey && !event.nativeEvent.isComposing) {
              event.preventDefault();
              void sendMessage();
            }
          }}
        />

        <div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-[color:var(--color-border-tertiary)] pt-3">
          <div className="flex flex-wrap items-center gap-2">
            <select
              className="chat-dataset-select h-9 rounded-[9px] border border-[color:var(--color-border-tertiary)] bg-[color:var(--color-background-primary)] px-3 font-mono text-[12px] text-[color:var(--color-text-secondary)] outline-none ring-0 transition-colors hover:bg-[color:var(--color-button-hover-background)]"
              value={selectedDatasetId ?? ""}
              onChange={(event) => {
                const next = Number(event.target.value);
                setSelectedDatasetId(Number.isFinite(next) && next > 0 ? next : undefined);
              }}
            >
              <option value="">{t("auto_dataset_selection")}</option>
              {datasets.map((dataset) => (
                <option key={dataset.id} value={dataset.id}>
                  {dataset.name} ({dataset.tableName})
                </option>
              ))}
            </select>

            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              disabled={uploading}
              className="grid h-9 w-9 place-items-center rounded-[9px] border border-[color:var(--color-border-tertiary)] bg-[color:var(--color-background-primary)] text-[color:var(--color-text-secondary)] transition-colors hover:bg-[color:var(--color-button-hover-background)] hover:text-[color:var(--color-text-primary)] disabled:opacity-60"
              title="上传数据集"
            >
              {uploading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Upload className="h-4 w-4" />}
            </button>

            <button
              type="button"
              onClick={() => {
                if (!datasets.length) {
                  toast.error(t("upload_dataset_first"));
                  return;
                }
                setWorkspaceName(`工作区-${new Date().toISOString().slice(0, 10)}`);
                setWorkspaceDesc("");
                setPromoteOpen(true);
              }}
              className="grid h-9 w-9 place-items-center rounded-[9px] border border-[color:var(--color-border-tertiary)] bg-[color:var(--color-background-primary)] text-[color:var(--color-text-secondary)] transition-colors hover:bg-[color:var(--color-button-hover-background)] hover:text-[color:var(--color-text-primary)]"
              title="转为工作区"
            >
              <FolderUp className="h-4 w-4" />
            </button>
          </div>

          <button
            type="button"
            onClick={() => void sendMessage()}
            disabled={analyzing || !input.trim()}
            className="grid h-11 w-11 place-items-center rounded-[10px] bg-[color:var(--color-accent-highlight)] text-white transition-[filter,transform] hover:brightness-[0.96] active:scale-[0.98] disabled:opacity-50"
            title="发送"
          >
            {analyzing ? <Loader2 className="h-4 w-4 animate-spin" /> : <ArrowUp className="h-4 w-4" />}
          </button>
        </div>
        </div>
      </div>
    </div>
  );

  if (isEmptyState) {
    return (
      <div className="relay-frame flex h-full min-h-[calc(100vh-3rem)] flex-col border-0">
        <div className="flex w-full flex-1 items-center justify-center px-6 py-10">
          {composer}
        </div>

        <input
          ref={fileInputRef}
          type="file"
          accept=".csv,.xlsx,.xls"
          className="hidden"
          onChange={(event) => {
            const file = event.target.files?.[0];
            void triggerUpload(file);
            if (event.target) event.target.value = "";
          }}
        />

        <Dialog open={promoteOpen} onOpenChange={setPromoteOpen}>
          <DialogContent className="max-w-2xl">
            <DialogHeader>
              <DialogTitle>{t("promote_dialog_title")}</DialogTitle>
              <DialogDescription>{t("promote_dialog_desc")}</DialogDescription>
            </DialogHeader>
            <div className="space-y-4">
              <Input value={workspaceName} onChange={(event) => setWorkspaceName(event.target.value)} placeholder={t("workspace_name")} />
              <Textarea
                value={workspaceDesc}
                onChange={(event) => setWorkspaceDesc(event.target.value)}
                placeholder={t("description_optional")}
                rows={6}
              />
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setPromoteOpen(false)}>
                {t("cancel")}
              </Button>
              <Button onClick={() => void promoteToWorkspace()} disabled={promoting}>
                {promoting ? <Loader2 className="h-4 w-4 animate-spin" /> : <FolderUp className="h-4 w-4" />}
                {t("promote")}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    );
  }

  return (
      <div className="relay-frame flex h-full min-h-[calc(100vh-3rem)] flex-col border-0">
      <div className="flex w-full flex-1 flex-col px-6 pb-6 pt-10">
        <div
          ref={scrollRef}
          className="flex-1 overflow-y-auto"
        >
            <div className="mx-auto max-w-[820px] space-y-8 pb-8">
            {loadingMessages ? (
              <>
                <Skeleton className="ml-auto h-16 w-[44%]" />
                <Skeleton className="h-16 w-[58%]" />
                <Skeleton className="h-28 w-[68%]" />
              </>
            ) : null}

            {!loadingMessages &&
              messages.map((message) => {
                const isUser = message.role.toUpperCase() === "USER";
                return (
                  <div key={message.id} className={cn("flex", isUser ? "justify-end" : "justify-start")}>
                    <div
                      className={cn(
                        "max-w-[78%] px-1 text-[15px] leading-8",
                        isUser
                          ? "relay-user-bubble px-5 py-3 font-medium shadow-none"
                          : "text-[color:var(--color-text-secondary)]"
                      )}
                    >
                      {message.content}
                    </div>
                  </div>
                );
              })}

            {!loadingMessages && lastResult && !messages.some((message) => message.role.toUpperCase() === "ASSISTANT") ? (
              <div className="flex justify-start">
                <div className="max-w-[760px] px-1">
                  {lastResult.summary ? (
                    <article className="whitespace-pre-wrap border-l-2 border-[color:var(--color-accent-highlight)] pl-5 text-[15px] leading-8 text-[color:var(--color-text-primary)]">
                      {lastResult.summary}
                    </article>
                  ) : null}

                  <ResultTable rows={lastResult.data ?? []} />

                  {lastResult.generatedCodeOrSql || lastResult.generatedSql ? (
                    <div className="mt-4">
                      <button
                        type="button"
                        onClick={() => setShowCode((prev) => !prev)}
                        className="text-sm text-[color:var(--color-text-secondary)] transition-colors hover:text-[color:var(--color-text-primary)]"
                      >
                        {showCode ? "隐藏代码" : "查看代码"}
                      </button>
                      {showCode ? (
                        <pre className="relay-code mt-3 overflow-x-auto whitespace-pre-wrap px-4 py-4 text-sm leading-7">
                          {lastResult.generatedCodeOrSql || lastResult.generatedSql}
                        </pre>
                      ) : null}
                    </div>
                  ) : null}
                </div>
              </div>
            ) : null}

            {!loadingMessages && !hasConversation && previewArtifacts.length ? (
              <div className="space-y-3 pt-2">
                <div className="text-xs uppercase tracking-[0.12em] text-[color:var(--color-text-tertiary)]">Recent</div>
                <div className="grid gap-3 sm:grid-cols-2">
                  {previewArtifacts.map((artifact) => (
                    <button
                      key={artifact.id}
                      type="button"
                      onClick={() => {
                        setInput(artifact.userQuery ?? "");
                        setLastResult({
                          success: true,
                          data: parsePreview(artifact.resultPreviewJson),
                          generatedCodeOrSql: artifact.generatedCodeOrSql,
                          summary: artifact.summary,
                          recommendedChart: artifact.chartType,
                          artifactId: artifact.id,
                        });
                      }}
                      className="relay-panel-soft px-4 py-4 text-left transition-colors hover:border-[color:var(--color-border-info)] hover:bg-[color:var(--color-background-primary)]"
                    >
                      <div className="line-clamp-2 text-sm font-medium text-[color:var(--color-text-primary)]">
                        {artifact.userQuery || t("artifact_query")}
                      </div>
                      <div className="mt-2 line-clamp-3 text-sm leading-6 text-[color:var(--color-text-secondary)]">
                        {artifact.summary || "无摘要"}
                      </div>
                      <div className="mt-3 text-xs text-[color:var(--color-text-tertiary)]">
                        {formatTime(artifact.createdAt, localeTag)}
                      </div>
                    </button>
                  ))}
                </div>
              </div>
            ) : null}
          </div>
        </div>

        <div className="mx-auto mt-4 w-full max-w-[760px]">{composer}</div>
      </div>

      <input
        ref={fileInputRef}
        type="file"
        accept=".csv,.xlsx,.xls"
        className="hidden"
        onChange={(event) => {
          const file = event.target.files?.[0];
          void triggerUpload(file);
          if (event.target) event.target.value = "";
        }}
      />

      <Dialog open={promoteOpen} onOpenChange={setPromoteOpen}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>{t("promote_dialog_title")}</DialogTitle>
            <DialogDescription>{t("promote_dialog_desc")}</DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <Input value={workspaceName} onChange={(event) => setWorkspaceName(event.target.value)} placeholder={t("workspace_name")} />
            <Textarea
              value={workspaceDesc}
              onChange={(event) => setWorkspaceDesc(event.target.value)}
              placeholder={t("description_optional")}
              rows={6}
            />
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setPromoteOpen(false)}>
              {t("cancel")}
            </Button>
            <Button onClick={() => void promoteToWorkspace()} disabled={promoting}>
              {promoting ? <Loader2 className="h-4 w-4 animate-spin" /> : <FolderUp className="h-4 w-4" />}
              {t("promote")}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

export default function ChatPage() {
  return (
    <Suspense fallback={null}>
      <ChatPageContent />
    </Suspense>
  );
}
